# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20170410_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='freeTrans',
        ),
        migrations.RemoveField(
            model_name='word',
            name='freeTrans2',
        ),
        migrations.RemoveField(
            model_name='word',
            name='freeTrans2Example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='freeTransExample',
        ),
        migrations.RemoveField(
            model_name='word',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='word',
            name='wordExample',
        ),
        migrations.AddField(
            model_name='word',
            name='POS',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='word',
            name='dialect',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='word',
            name='gloss',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='word',
            name='no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='word',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='prefix',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='stem',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='tone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='word_class',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=511),
        ),
    ]
